import { useEffect, useState } from 'react';
import { View } from 'react-native';
import { Text, TextInput, Button, Checkbox } from 'react-native-paper';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useLocalSearchParams } from 'expo-router';
import * as Crypto from 'expo-crypto';
import { useAuthStore } from '../store/auth';
import { apiClient } from '../api/client';
import { WorkflowPage, flowStyles as s } from '../components/common/WorkflowPage';
export default function SupportAndOperations() {
 const actor=useAuthStore(state=>state.user),admin=actor?.role==='ADMIN',patient=actor?.role==='PATIENT',qc=useQueryClient();
 const params=useLocalSearchParams<{paymentId?:string;visitId?:string}>();
 const [page,setPage]=useState(1),[userPage,setUserPage]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [draft,setDraft]=useState({requestKey:Crypto.randomUUID(),kind:'DISPUTE',paymentId:params.paymentId || '',visitId:params.visitId || '',amount:'',reason:''});
 const [notes,setNotes]=useState<Record<string,string>>({}),[references,setReferences]=useState<Record<string,string>>({}),[dates,setDates]=useState<Record<string,string>>({});
 const [permission,setPermission]=useState({role:'PATIENT',feature:'ANALYTICS',operation:'READ',allowed:true,reason:''});
 const [edit,setEdit]=useState({id:'',fullName:'',phone:'',reason:''});
 const cases=useQuery({queryKey:['support-cases',actor?.id,page],queryFn:()=>apiClient.get<any>(`/support/cases?page=${page}`),enabled:!!(admin || patient),refetchInterval:30000});
 const extras=useQuery({queryKey:['support-extras',actor?.id,userPage],queryFn:async()=>{
  if(admin){const [payments,permissions,monitor,users]=await Promise.all([apiClient.get<any>('/admin/payments'),apiClient.get<any>('/admin/permissions'),apiClient.get<any>('/admin/operations/monitor'),apiClient.get<any>(`/admin/users?limit=20&page=${userPage}`)]);return {payments:payments.items,permissions,monitor,users:users.users,userTotal:users.total,visits:[]};}
  const [payments,requests]=await Promise.all([apiClient.get<any[]>(`/patients/${actor!.patientId}/payments`),apiClient.get<any[]>('/patients/requests')]);return {payments,visits:requests.flatMap(r=>r.visits || []),users:[],userTotal:0,permissions:null,monitor:null};
 },enabled:!!(admin || patient)});
 const permissionData=extras.data?.permissions;
 useEffect(()=>{if(!permissionData)return;setPermission(current=>{const saved=permissionData.overrides.find((p:any)=>p.role===current.role && p.feature===current.feature && p.operation===current.operation);return {...current,allowed:saved?saved.allowed:true};});},[permissionData]);
 const run=async(task:()=>Promise<unknown>,success:string)=>{setBusy(true);setError('');setMessage('');try{await task();setMessage(success);await qc.invalidateQueries({queryKey:['support-cases']});await extras.refetch();}catch(e:any){setError(e.message || 'Could not save');}finally{setBusy(false);}};
 const submit=()=>run(async()=>{await apiClient.post('/support/cases',{requestKey:draft.requestKey,kind:draft.kind,...(draft.paymentId?{paymentId:draft.paymentId}:{}),...(draft.visitId?{visitId:draft.visitId}:{}),...(draft.kind==='REFUND'?{amount:Number(draft.amount)}:{}),reason:draft.reason});setDraft({...draft,requestKey:Crypto.randomUUID(),reason:'',amount:''});},'Support request recorded. No money is transferred by this form.');
 const update=(item:any,status:string)=>run(()=>apiClient.put(`/admin/support/cases/${item.id}`,{status,notes:notes[item.id] || '',...(status==='RECORDED'?{externalReference:references[item.id] || '',completedAt:dates[item.id] || ''}:{})}),'Support case updated.');
 if(!admin && !patient)return <WorkflowPage title="Support"><Text style={s.body}>Sign in as a patient or administrator to manage support cases.</Text></WorkflowPage>;
 return <WorkflowPage title={admin?'Administration operations':'Refunds and care concerns'} loading={cases.isLoading || extras.isLoading} error={error || cases.error?.message || extras.error?.message} retry={()=>{void cases.refetch();void extras.refetch();}}>
  {!!message && <Text style={s.body}>{message}</Text>}
  {patient && <View style={s.card}><Text style={s.title}>New support request</Text><View style={s.row}>{['DISPUTE','REFUND'].map(kind=><Button key={kind} mode={draft.kind===kind?'contained':'outlined'} onPress={()=>setDraft({...draft,kind,visitId:kind==='REFUND'?'':draft.visitId})}>{kind==='REFUND'?'Refund request':'Care concern'}</Button>)}</View>
   <Text style={s.body}>Choose your recorded payment or visit.</Text>{extras.data && extras.data.payments.length===0 && <Text style={s.body}>No payment records available.</Text>}{draft.kind==='DISPUTE' && extras.data && extras.data.visits.length===0 && <Text style={s.body}>No visit records available. A concern must relate to one of your visits or payments.</Text>}{extras.data?.payments.map((p:any)=><Button key={p.id} mode={draft.paymentId===p.id?'contained':'outlined'} onPress={()=>setDraft({...draft,paymentId:p.id,visitId:''})}>PKR {p.amount} · {p.status} · {p.id.slice(0,8)}</Button>)}
   {draft.kind==='DISPUTE' && extras.data?.visits.map((v:any)=><Button key={v.id} mode={draft.visitId===v.id?'contained':'outlined'} onPress={()=>setDraft({...draft,visitId:v.id,paymentId:''})}>Visit {v.id.slice(0,8)} · {v.status}</Button>)}
   {draft.kind==='REFUND' && <TextInput label="Requested refund (PKR)" keyboardType="decimal-pad" value={draft.amount} onChangeText={amount=>setDraft({...draft,amount})}/>}<TextInput label="Reason (at least 10 characters)" multiline value={draft.reason} maxLength={5000} onChangeText={reason=>setDraft({...draft,reason})}/><Button disabled={busy || draft.reason.trim().length<10 || (!draft.paymentId && !draft.visitId)} onPress={()=>void submit()}>Submit support request</Button>
  </View>}
  <Text style={s.title}>Support cases</Text>{cases.data?.items.length===0 && <Text style={s.body}>No support cases recorded.</Text>}
  {cases.data?.items.map((item:any)=><View key={item.id} style={s.card}><Text style={s.title}>{item.kind} · {item.status} · {item.id.slice(0,8)}</Text><Text style={s.body}>{item.reason}</Text>{item.amount!=null && <Text style={s.body}>Requested amount: PKR {item.amount}</Text>}<Text style={s.body}>{new Date(item.createdAt).toLocaleString()}</Text>{item.decisionNotes && <Text style={s.body}>Staff response: {item.decisionNotes}</Text>}{item.externalReference && <Text style={s.body}>Externally completed refund recorded: {item.externalReference} · {item.resolvedAt}</Text>}
   {admin && !['RECORDED','RESOLVED','REJECTED'].includes(item.status) && <View><TextInput label="Decision notes (at least 10 characters)" multiline value={notes[item.id] || ''} onChangeText={text=>setNotes({...notes,[item.id]:text})}/>{item.kind==='REFUND' && item.status==='APPROVED' && <><Text style={s.body}>Record only a refund already completed outside Healix. This action does not transfer money.</Text><TextInput label="External refund reference" value={references[item.id] || ''} onChangeText={text=>setReferences({...references,[item.id]:text})}/><TextInput label="Actual completion time (ISO, e.g. 2026-10-06T09:00:00Z)" value={dates[item.id] || ''} onChangeText={text=>setDates({...dates,[item.id]:text})}/></>}<View style={s.row}>{(item.kind==='REFUND'?(item.status==='APPROVED'?['RECORDED','REJECTED']:['IN_REVIEW','APPROVED','REJECTED']):['IN_REVIEW','RESOLVED','REJECTED']).map(status=><Button disabled={busy} key={status} onPress={()=>void update(item,status)}>{status==='RECORDED'?'Record external refund':status.replaceAll('_',' ')}</Button>)}</View></View>}
  </View>)}
  <View style={s.row}><Button disabled={page===1} onPress={()=>setPage(page-1)}>Previous</Button><Text style={s.body}>Page {page}</Text><Button disabled={!cases.data || page*cases.data.limit>=cases.data.total} onPress={()=>setPage(page+1)}>Next</Button></View>
  {admin && extras.data?.monitor && <View style={s.card}><Text style={s.title}>Operational monitor</Text>{Object.entries(extras.data.monitor).map(([key,value])=><Text key={key} style={s.body}>{key}: {String(value)}</Text>)}<Button onPress={()=>void extras.refetch()}>Refresh monitor</Button></View>}
  {admin && <View style={s.card}><Text style={s.title}>Edit a user profile</Text><View style={s.row}><Button disabled={userPage===1} onPress={()=>setUserPage(userPage-1)}>Previous users</Button><Text style={s.body}>Users page {userPage}</Text><Button disabled={!extras.data || userPage*20>=extras.data.userTotal} onPress={()=>setUserPage(userPage+1)}>Next users</Button></View>{extras.data?.users.map((u:any)=><Button key={u.id} onPress={()=>setEdit({id:u.id,fullName:u.fullName,phone:u.phone,reason:''})}>{u.fullName} · {u.role}</Button>)}{!!edit.id && <><TextInput label="Full name" value={edit.fullName} onChangeText={fullName=>setEdit({...edit,fullName})}/><TextInput label="Phone" value={edit.phone} onChangeText={phone=>setEdit({...edit,phone})}/><TextInput label="Audit reason" value={edit.reason} onChangeText={reason=>setEdit({...edit,reason})}/><Button disabled={busy} onPress={()=>void run(()=>apiClient.put(`/admin/users/${edit.id}/profile`,{fullName:edit.fullName,phone:edit.phone,reason:edit.reason}),'Profile updated.')}>Save profile</Button></>}</View>}
  {admin && extras.data?.permissions && <View style={s.card}><Text style={s.title}>Role capabilities</Text><Text style={s.body}>{extras.data.permissions.rule}</Text>{['role','feature','operation'].map(field=><View key={field} style={s.row}>{(field==='role'?extras.data!.permissions.roles:field==='feature'?extras.data!.permissions.features:['READ','WRITE']).map((value:string)=><Button key={value} mode={(permission as any)[field]===value?'contained':'outlined'} onPress={()=>{const next={...permission,[field]:value};const saved=extras.data!.permissions.overrides.find((p:any)=>p.role===next.role && p.feature===next.feature && p.operation===next.operation);setPermission({...next,allowed:saved?saved.allowed:true});}}>{value}</Button>)}</View>)}<Checkbox.Item label="Enable within built-in role and ownership checks" status={permission.allowed?'checked':'unchecked'} onPress={()=>setPermission({...permission,allowed:!permission.allowed})}/><TextInput label="Audit reason" value={permission.reason} onChangeText={reason=>setPermission({...permission,reason})}/><Button disabled={busy} onPress={()=>void run(()=>apiClient.put('/admin/permissions',permission),'Role capability updated.')}>Save capability</Button></View>}
  {admin && <View style={s.card}><Text style={s.title}>Recorded payments</Text><Text style={s.body}>Application records, without bank reconciliation. Use web administration to record an externally settled commission.</Text>{extras.data?.payments.map((p:any)=><Text key={p.id} style={s.body}>{p.id} · PKR {p.amount} · {p.status} · Commission: {p.commissionAmount ?? 'Not recorded'}</Text>)}</View>}
 </WorkflowPage>;
}
