import { useEffect, useState } from 'react';
import { api } from '../../store/auth';
export default function Operations() {
 const [data,setData]=useState<any>(),[page,setPage]=useState(1),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [notes,setNotes]=useState<Record<string,string>>({}),[refs,setRefs]=useState<Record<string,string>>({}),[times,setTimes]=useState<Record<string,string>>({});
 const [edit,setEdit]=useState({id:'',fullName:'',phone:'',reason:''});
 const [permission,setPermission]=useState({role:'PATIENT',feature:'ANALYTICS',operation:'READ',allowed:true,reason:''});
 const [commission,setCommission]=useState({paymentId:'',amount:'',reference:'',recordedAt:'',reason:''});
 const refresh=async()=>{const [cases,payments,permissions,monitor,users]=await Promise.all([api('GET',`/support/cases?page=${page}`),api('GET',`/admin/payments?page=${page}`),api('GET','/admin/permissions'),api('GET','/admin/operations/monitor'),api('GET',`/admin/users?limit=20&page=${page}`)]);setData({cases,payments,permissions,monitor,users});};
 useEffect(()=>{if(!data?.permissions)return;setPermission(current=>{const saved=data.permissions.overrides.find((p:any)=>p.role===current.role && p.feature===current.feature && p.operation===current.operation);return {...current,allowed:saved?saved.allowed:true};});},[data?.permissions]);
 useEffect(()=>{void refresh().catch(e=>setError(e.message));},[page]);
 const run=async(task:()=>Promise<unknown>,success:string)=>{setBusy(true);setError('');setMessage('');try{await task();setMessage(success);await refresh();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const update=(item:any,status:string)=>run(()=>api('PUT',`/admin/support/cases/${item.id}`,{status,notes:notes[item.id] || '',...(status==='RECORDED'?{externalReference:refs[item.id] || '',completedAt:times[item.id] || ''}:{})}),'Support case updated.');
 return <div className="page"><h1>Administration operations</h1>{error && <p role="alert">{error}</p>}{message && <p role="status">{message}</p>}{!data && <p>Loading operations…</p>}
  {data && <>
   <section className="card"><h2>Operational monitor</h2><dl>{Object.entries(data.monitor).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{String(value)}</dd></div>)}</dl><button onClick={()=>void refresh().catch(e=>setError(e.message))}>Refresh</button></section>
   <section className="card"><h2>Edit user profile</h2><label>User<select value={edit.id} onChange={e=>{const user=data.users.users.find((u:any)=>u.id===e.target.value);if(user)setEdit({id:user.id,fullName:user.fullName,phone:user.phone,reason:''});}}><option value="">Select user</option>{data.users.users.map((u:any)=><option value={u.id} key={u.id}>{u.fullName} · {u.role}</option>)}</select></label>{edit.id && <form onSubmit={e=>{e.preventDefault();void run(()=>api('PUT',`/admin/users/${edit.id}/profile`,{fullName:edit.fullName,phone:edit.phone,reason:edit.reason}),'User profile updated.');}}><label>Name<input required value={edit.fullName} onChange={e=>setEdit({...edit,fullName:e.target.value})}/></label><label>Phone<input required value={edit.phone} onChange={e=>setEdit({...edit,phone:e.target.value})}/></label><label>Audit reason<input required minLength={10} value={edit.reason} onChange={e=>setEdit({...edit,reason:e.target.value})}/></label><button disabled={busy}>Save profile</button></form>}</section>
   <section className="card"><h2>Role capabilities</h2><p>{data.permissions.rule}</p><form onSubmit={e=>{e.preventDefault();void run(()=>api('PUT','/admin/permissions',permission),'Role capability saved.');}}>{['role','feature','operation'].map(field=><label key={field}>{field}<select value={(permission as any)[field]} onChange={e=>{const next={...permission,[field]:e.target.value};const saved=data.permissions.overrides.find((p:any)=>p.role===next.role && p.feature===next.feature && p.operation===next.operation);setPermission({...next,allowed:saved?saved.allowed:true});}}>{(field==='role'?data.permissions.roles:field==='feature'?data.permissions.features:['READ','WRITE']).map((value:string)=><option key={value}>{value}</option>)}</select></label>)}<label><input type="checkbox" checked={permission.allowed} onChange={e=>setPermission({...permission,allowed:e.target.checked})}/>Enable within built-in role and ownership checks</label><label>Audit reason<input required minLength={10} value={permission.reason} onChange={e=>setPermission({...permission,reason:e.target.value})}/></label><button disabled={busy}>Save capability</button></form></section>
   <section className="card"><h2>Refund requests and disputes</h2>{data.cases.items.length===0 && <p>No cases recorded.</p>}{data.cases.items.map((item:any)=><article key={item.id}><h3>{item.kind} · {item.status} · {item.id.slice(0,8)}</h3><p>{item.reason}</p>{item.amount!=null && <p>Requested refund: PKR {item.amount}</p>}{item.decisionNotes && <p>Staff response: {item.decisionNotes}</p>}{item.externalReference && <p>Recorded external refund: {item.externalReference} · {item.resolvedAt}</p>}{!['RECORDED','RESOLVED','REJECTED'].includes(item.status) && <><label>Decision notes<textarea value={notes[item.id] || ''} onChange={e=>setNotes({...notes,[item.id]:e.target.value})}/></label>{item.kind==='REFUND' && item.status==='APPROVED' && <><p>Record only a refund already completed outside Healix. Recording does not transfer money.</p><label>External refund reference<input value={refs[item.id] || ''} onChange={e=>setRefs({...refs,[item.id]:e.target.value})}/></label><label>Actual completion time (ISO)<input placeholder="2026-10-06T09:00:00Z" value={times[item.id] || ''} onChange={e=>setTimes({...times,[item.id]:e.target.value})}/></label></>}{(item.kind==='REFUND'?(item.status==='APPROVED'?['RECORDED','REJECTED']:['IN_REVIEW','APPROVED','REJECTED']):['IN_REVIEW','RESOLVED','REJECTED']).map(status=><button key={status} disabled={busy} onClick={()=>void update(item,status)}>{status==='RECORDED'?'Record external refund':status.replaceAll('_',' ')}</button>)}</>}</article>)}</section>
   <section className="card"><h2>Recorded payment monitoring</h2><p>{data.payments.recordBasis}</p><div style={{overflowX:'auto'}}><table><thead><tr><th>Payment</th><th>Patient</th><th>Amount</th><th>Status</th><th>Commission</th></tr></thead><tbody>{data.payments.items.map((p:any)=><tr key={p.id}><td>{p.id}</td><td>{p.request.patient.user.fullName}</td><td>PKR {p.amount}</td><td>{p.status}</td><td>{p.commissionAmount==null?'Not recorded':`PKR ${p.commissionAmount}`}</td></tr>)}</tbody></table></div>
    <h3>Record an externally settled commission</h3><p>Enter the actual settled amount, date and reference. This does not charge a fee or move money.</p><form onSubmit={e=>{e.preventDefault();void run(()=>api('PUT',`/admin/payments/${commission.paymentId}/commission`,{amount:Number(commission.amount),reference:commission.reference,recordedAt:commission.recordedAt,reason:commission.reason}),'External commission recorded.');}}><label>Paid payment<select required value={commission.paymentId} onChange={e=>setCommission({...commission,paymentId:e.target.value})}><option value="">Select payment</option>{data.payments.items.filter((p:any)=>p.status==='PAID' && p.commissionAmount==null).map((p:any)=><option key={p.id} value={p.id}>{p.id} · PKR {p.amount}</option>)}</select></label>{['amount','reference','recordedAt','reason'].map(field=><label key={field}>{field}<input required type={field==='amount'?'number':'text'} min={field==='amount'?0:undefined} step={field==='amount'?'0.01':undefined} value={(commission as any)[field]} onChange={e=>setCommission({...commission,[field]:e.target.value})}/></label>)}<button disabled={busy}>Record commission</button></form>
   </section>
   <div><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button> Page {page} <button disabled={page*20>=Math.max(data.cases.total,data.payments.total,data.users.total)} onClick={()=>setPage(page+1)}>Next</button></div>
  </>}
 </div>;
}
