import React from 'react';
import { StyleSheet, View, ScrollView, TouchableOpacity, SafeAreaView, StatusBar, Alert } from 'react-native';
import { Text } from 'react-native-paper';
import { useRouter } from 'expo-router';
import { useAuthStore } from '../../../store/auth';
import { usePrescriptions } from '../../../hooks/useHealth';
import { SPACING, TYPOGRAPHY } from '../../../theme';

import { PrescriptionCard } from '../../../components/patient/PrescriptionCard';
import { LoadingState } from '../../../components/common/LoadingState';
import { ErrorState } from '../../../components/common/ErrorState';

export default function PrescriptionsScreen() {
  const router = useRouter();
  const { user } = useAuthStore();
  const patientId = user?.patientId || '';

  const { data: prescriptions, isLoading, error, refetch } = usePrescriptions(patientId);

  const handleDownload = (fileUrl?: string) => {
    if (fileUrl) {
      Alert.alert('Download', `Downloading prescription PDF from ${fileUrl}`);
    } else {
      Alert.alert('Notice', 'Prescription file link is being generated by the doctor.');
    }
  };

  if (isLoading && !prescriptions) return <LoadingState message="Loading prescriptions..." />;
  if (error) return <ErrorState error={error as Error} onRetry={refetch} />;

  return (
    <SafeAreaView style={styles.safeArea}>
      <StatusBar barStyle="light-content" backgroundColor="#061C19" />
      <View style={styles.container}>
        {/* Header */}
        <View style={styles.headerRow}>
          <TouchableOpacity style={styles.backBtn} onPress={() => router.back()}>
            <Text style={styles.backIcon}>‹</Text>
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Prescriptions</Text>
          <View style={{ width: 40 }} />
        </View>

        <ScrollView contentContainerStyle={styles.listContainer} showsVerticalScrollIndicator={false}>
          {prescriptions && prescriptions.length > 0 ? (
            prescriptions.map((pres: any) => (
              <PrescriptionCard
                key={pres.id}
                doctorName={pres.doctor?.user?.fullName || 'Physician'}
                prescribedAt={pres.prescribedAt ? new Date(pres.prescribedAt).toLocaleDateString() : 'Issued'}
                instructions={pres.instructions}
                fileUrl={pres.fileUrl}
                onDownload={() => handleDownload(pres.fileUrl)}
              />
            ))
          ) : (
            <View style={styles.emptyState}>
              <Text style={styles.emptyIcon}>💊</Text>
              <Text style={styles.emptyTitle}>No Prescriptions Found</Text>
              <Text style={styles.emptySub}>
                Doctor-issued prescriptions and treatment plans will appear here.
              </Text>
            </View>
          )}
        </ScrollView>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#061C19',
  },
  container: {
    flex: 1,
    padding: SPACING.lg,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: SPACING.lg,
  },
  backBtn: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backIcon: {
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: '300',
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: TYPOGRAPHY.sizes.lg,
    fontWeight: '700',
  },
  listContainer: {
    paddingBottom: 40,
    gap: SPACING.md,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 60,
    paddingHorizontal: 20,
  },
  emptyIcon: {
    fontSize: 44,
    marginBottom: 12,
  },
  emptyTitle: {
    color: '#FFFFFF',
    fontSize: TYPOGRAPHY.sizes.md,
    fontWeight: '700',
  },
  emptySub: {
    color: '#94A3B8',
    fontSize: 11,
    textAlign: 'center',
    marginTop: 6,
    lineHeight: 16,
  },
});

