import { useEffect, useState } from 'react';
import { api, useAuthStore } from '../store/auth';
export default function Analytics() {
 const [data,setData]=useState<any>(),[from,setFrom]=useState(''),[to,setTo]=useState(''),[period,setPeriod]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const actor=useAuthStore(state=>state.user),admin=actor?.role==='ADMIN';
 const [staffRole,setStaffRole]=useState('NURSE'),[staffPage,setStaffPage]=useState(1),[staffUserId,setStaffUserId]=useState(''),[staff,setStaff]=useState<any>();
 useEffect(()=>{if(!admin)return;let current=true;api('GET',`/admin/users?role=${staffRole}&page=${staffPage}&limit=20`).then(value=>{if(current)setStaff(value);}).catch(e=>{if(current)setError(e.message);});return()=>{current=false;};},[admin,staffRole,staffPage]);
 const token=useAuthStore(state=>state.token);
 useEffect(()=>{let current=true;setLoading(true);setError('');setData(undefined);api('GET','/analytics/overview'+period).then(value=>{if(current)setData(value);}).catch(e=>{if(current)setError(e.message);}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[period,token]);
 const download=async()=>{try{const response=await fetch('/api/v1/analytics/report.csv'+period,{headers:{Authorization:'Bearer '+token}});if(!response.ok)throw new Error('Could not export this report');const url=URL.createObjectURL(await response.blob());const link=document.createElement('a');link.href=url;link.download='Healix_Report.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e:any){setError(e.message);}};
 return <div className="page-content"><h1>Analytics and reports</h1><p>Dates and daily grouping use UTC. Reports use recorded application data.</p><div className="card">{admin && <div><h2>Staff performance monitoring</h2><label>Staff role<select value={staffRole} onChange={e=>{setStaffRole(e.target.value);setStaffPage(1);setStaffUserId('');}}><option>NURSE</option><option>DOCTOR</option></select></label><label>Staff member<select value={staffUserId} onChange={e=>setStaffUserId(e.target.value)}><option value="">Platform report</option>{staff?.users.map((user:any)=><option value={user.id} key={user.id}>{user.fullName}</option>)}</select></label><button disabled={staffPage===1} onClick={()=>setStaffPage(staffPage-1)}>Previous staff</button><span> Staff page {staffPage} </span><button disabled={!staff || staffPage*20>=staff.total} onClick={()=>setStaffPage(staffPage+1)}>Next staff</button><p>Select a staff member and apply the period.</p></div>}<label>From <input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To <input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={()=>setPeriod('?'+new URLSearchParams({...from?{from}:{},...to?{to}:{},...(admin && staffUserId?{staffUserId}:{})}).toString())}>Apply period</button><button disabled={!data} onClick={()=>void download()}>Export CSV</button></div>{loading && <p>Loading report…</p>}{error && <p role="alert">{error}</p>}{data && <><p>{data.period.from} – {data.period.to} · {data.role}</p><div className="stats-grid">{data.metrics.map((m:any)=><div className="stat-card" key={m.label}><div className="stat-value">{m.value==null?'No data':m.value}</div><div className="stat-label">{m.label} {m.unit}</div></div>)}</div>{data.tables.map((table:any)=><section className="card" key={table.title}><h2>{table.title}</h2>{table.rows.length?<div style={{overflowX:'auto'}}><table className="data-table"><thead><tr>{Object.keys(table.rows[0]).map(column=><th key={column}>{column}</th>)}</tr></thead><tbody>{table.rows.slice(0,200).map((row:any,index:number)=><tr key={index}>{Object.entries(row).map(([key,value])=><td key={key}>{String(value??'No data')}</td>)}</tr>)}</tbody></table>{table.rows.length>200 && <p>Showing 200 of {table.rows.length} records. Export CSV for all records.</p>}</div>:<p>No recorded data in this period.</p>}</section>)}{data.limitations.map((text:string)=><p key={text}>{text}</p>)}</>}</div>;
}
