import { useCallback, useEffect, useState } from 'react';
import ClinicalDecision from '../components/ClinicalDecision';
import { api, useAuthStore } from '../store/auth';

const transitions: Record<string, string[]> = { PENDING: ['DISPATCHED', 'CANCELLED'], DISPATCHED: ['EN_ROUTE', 'ARRIVED', 'CANCELLED'], EN_ROUTE: ['ARRIVED', 'CANCELLED'], ARRIVED: ['COMPLETED', 'CANCELLED'] };
const vehicleDefaults = { vehicleNumber: '', plateNumber: '', type: 'BASIC', provider: 'Healix Fleet', contactNumber: '', status: 'AVAILABLE' };
const hospitalDefaults = { name: '', latitude: '', longitude: '', capacityStatus: 'AVAILABLE', affordabilityTier: 'LOW', isCharity: false };
export default function EmergencyOperations() {
  const admin = useAuthStore(s => s.user?.role === 'ADMIN');
  const [selectedEvent, setSelectedEvent] = useState<any>(null);
  const [dispatches, setDispatches] = useState<any[]>([]);
  const [fleet, setFleet] = useState<any[]>([]);
  const [hospitals, setHospitals] = useState<any[]>([]);
  const [events, setEvents] = useState<any[]>([]);
  const [cases, setCases] = useState<any[]>([]);
  const [doctors, setDoctors] = useState<any[]>([]);
  const [paramedics, setParamedics] = useState<any[]>([]);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const [loaded, setLoaded] = useState(false);
  const [vehicle, setVehicle] = useState<any>(null);
  const [hospital, setHospital] = useState<any>(null);
  const [history, setHistory] = useState(false);
  const [confirmation, setConfirmation] = useState<{ title: string; run: (notes: string) => Promise<unknown> } | null>(null);
  const [notes, setNotes] = useState('');
  const refresh = useCallback(async () => {
    try {
      const results = await Promise.all([api('GET', '/dispatch'), ...(admin ? [api('GET', '/admin/ambulances'), api('GET', '/admin/hospitals'), api('GET', '/admin/emergencies'), api('GET', '/admin/doctors'), api('GET', '/admin/users?role=PARAMEDIC&limit=100'), api('GET', '/admin/cases')] : [api('GET', '/emergency/events')])]);
      setDispatches(results[0]);
      if (admin) { setFleet(results[1]); setHospitals(results[2]); setEvents(results[3]); setDoctors(results[4]); setParamedics(results[5].users); setCases(results[6]); } else setEvents(results[1]);
      setLoaded(true);
    } catch (e: any) { setError(e.message || 'Could not load emergency operations'); }
  }, [admin]);
  useEffect(() => { let cancelled = false; void refresh(); const timer = setInterval(() => { if (!cancelled) void refresh(); }, 10000); return () => { cancelled = true; clearInterval(timer); }; }, [refresh]);
  const run = async (task: () => Promise<unknown>) => { setBusy(true); setError(''); try { await task(); await refresh(); setConfirmation(null); } catch (e: any) { setError(e.message); } finally { setBusy(false); } };
  const confirm = (title: string, task: (notes: string) => Promise<unknown>) => { setNotes(''); setConfirmation({ title, run: task }); };
  return <div className="page">
    <div className="page-header"><h2 className="page-title">{admin ? 'Emergency Center & Ambulance Fleet' : 'Emergency Dispatches & Admissions'}</h2><p>Dispatch updates refresh every 10 seconds. Vehicle locations are supplied by the assigned paramedic.</p><button className="btn btn-ghost" onClick={() => void refresh()}>Refresh</button></div>
    {error && <div role="alert" className="card" style={{ color: 'var(--red)' }}>{error}</div>}
    {!loaded && !error && <p>Loading operations…</p>}
    {admin && <>
      <div className="card"><h3>Ambulance Fleet</h3><p>Available: {fleet.filter(v => v.status === 'AVAILABLE').length} · Dispatched: {fleet.filter(v => v.status === 'DISPATCHED').length} · Inactive: {fleet.filter(v => v.status === 'INACTIVE').length}</p><button className="btn btn-primary" onClick={() => setVehicle({ ...vehicleDefaults })}>Register Ambulance</button>
        <table className="data-table"><thead><tr><th>Vehicle</th><th>Plate</th><th>Type / Provider</th><th>Status</th><th>Actions</th></tr></thead><tbody>{fleet.map(v => <tr key={v.id}><td>{v.vehicleNumber}</td><td>{v.plateNumber}</td><td>{v.type} / {v.provider}</td><td>{v.status}</td><td><button className="btn btn-ghost" disabled={busy} onClick={() => setVehicle({ ...v })}>Edit</button><button className="btn btn-danger" disabled={busy} onClick={() => confirm('Delete unused ambulance?', () => api('DELETE', `/admin/ambulances/${v.id}`))}>Delete</button></td></tr>)}</tbody></table>{!fleet.length && <p>No ambulances registered.</p>}
      </div>
      <div className="card"><h3>Hospital Network</h3><button className="btn btn-primary" onClick={() => setHospital({ ...hospitalDefaults })}>Add Hospital</button>
        <table className="data-table"><thead><tr><th>Hospital</th><th>Capacity</th><th>Budget</th><th>Capacity Updated</th><th>Actions</th></tr></thead><tbody>{hospitals.map(h => <tr key={h.id}><td>{h.name}</td><td>{h.capacityStatus}</td><td>{h.isCharity ? 'Charity' : h.affordabilityTier}</td><td>{new Date(h.capacityUpdatedAt).toLocaleString()}</td><td><button className="btn btn-ghost" onClick={() => setHospital({ ...h })}>Edit / Update Capacity</button><button className="btn btn-danger" onClick={() => confirm('Delete hospital with no dispatch history?', () => api('DELETE', `/admin/hospitals/${h.id}`))}>Delete</button></td></tr>)}</tbody></table>
      </div>
      <div className="card"><h3>Emergency Escalations</h3>{events.filter(e => !['RESOLVED', 'CANCELLED'].includes(e.status)).map(e => <div key={e.id} className="card"><strong>{e.patientName} · {e.severity}</strong><p>{e.status} · {e.slaBreach ? 'Response deadline breached' : 'Awaiting response / active'} · Doctor: {e.assignedDoctorName || e.assignedDoctorId || 'Unassigned'}</p><select className="form-input" value="" disabled={busy} onChange={ev => { const doctorId = ev.target.value; confirm('Assign this doctor to the emergency?', () => api('POST', `/admin/emergencies/${e.id}/assign-doctor`, { doctorId })); }}><option value="">Assign / change doctor</option>{doctors.filter(d => d.verificationStatus === 'VERIFIED' && d.user.status === 'ACTIVE').map(d => <option key={d.id} value={d.id}>{d.user.fullName}</option>)}</select><button className="btn btn-danger" disabled={busy} onClick={() => confirm('Escalate to critical severity?', () => api('PUT', `/admin/emergencies/${e.id}/escalate`, {}))}>Escalate</button><button className="btn btn-success" disabled={busy} onClick={() => confirm('Resolve emergency and close its active dispatches?', note => api('PUT', `/admin/emergencies/${e.id}/resolve`, { notes: note }))}>Resolve</button></div>)}
        {cases.filter(c => ['PROFESSIONAL_BROADCAST', 'GENERAL_BROADCAST', 'ADMIN_ESCALATED'].includes(c.status)).map(c => <div key={c.id} className="card"><strong>{c.visit?.request?.patient?.user?.fullName || 'Case'} · {c.riskTier}</strong><p>{c.status} · Case #{c.id.slice(0, 8)}</p><select className="form-input" value="" disabled={busy} onChange={ev => { const doctorId = ev.target.value; confirm('Assign this escalated case?', note => api('PUT', '/admin/cases/override-assignment', { caseId: c.id, doctorId, reason: note || 'Admin emergency assignment' })); }}><option value="">Select doctor</option>{doctors.filter(d => d.verificationStatus === 'VERIFIED' && d.user.status === 'ACTIVE').map(d => <option key={d.id} value={d.id}>{d.user.fullName}</option>)}</select></div>)}
      </div>
    </>}
    {!admin && <div className="card"><h3>Assigned Emergencies Awaiting Transport</h3>{events.filter(e => !e.dispatches.length).map(e => <div className="card" key={e.id}><strong>{e.patient.user.fullName} · {e.severity}</strong><button className="btn btn-primary" onClick={() => setSelectedEvent(e)}>Review Emergency Transport</button></div>)}{selectedEvent && <ClinicalDecision key={selectedEvent.id} patient={selectedEvent.patient} onSaved={() => { setSelectedEvent(null); void refresh(); }} />}</div>}
    <div className="card"><h3>Dispatches</h3><label><input type="checkbox" checked={history} onChange={e => setHistory(e.target.checked)} /> Show completed and cancelled records</label>
      {dispatches.filter(d => history || transitions[d.status]).map(d => {
        const active = !!transitions[d.status];
        const elapsed = Math.floor((Date.now() - Date.parse(d.etaUpdatedAt || d.dispatchedAt)) / 60000);
        return <div className="card" key={d.id}><h4>{d.patient.user.fullName} · {d.status}</h4><p>{d.ambulance?.vehicleNumber || 'No vehicle'} · {d.paramedic?.user.fullName || 'No paramedic'} → {d.hospital.name}</p><p>ETA estimate: {active ? Math.max(0, d.etaMinutes - elapsed) : 0} min ({d.etaUpdatedAt ? 'paramedic estimate' : 'initial estimate'})</p>
          {d.latitude != null && d.longitude != null ? <p><a href={`https://www.google.com/maps/search/?api=1&query=${d.latitude},${d.longitude}`} target="_blank" rel="noreferrer">View vehicle location</a> · {d.locationUpdatedAt ? new Date(d.locationUpdatedAt).toLocaleString() : 'Unknown timestamp'} · {!d.locationUpdatedAt || Date.now() - Date.parse(d.locationUpdatedAt) > 120000 ? 'STALE' : 'Recent'}</p> : <p>No vehicle location shared yet.</p>}
          {d.notes && <p>Notes: {d.notes}</p>}
          <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>{transitions[d.status]?.map(status => <button className="btn btn-ghost" key={status} disabled={busy} onClick={() => confirm(`Mark dispatch ${status}?`, note => api('PUT', `/dispatch/${d.id}/status`, { status, notes: note }))}>{status.replace('_', ' ')}</button>)}</div>
          {admin && active && <><select className="form-input" value="" disabled={busy} onChange={e => { const ambulanceId = e.target.value; confirm('Reassign available ambulance?', () => api('POST', `/admin/emergencies/${d.id}/assign-ambulance`, { ambulanceId })); }}><option value="">Select available ambulance</option>{fleet.filter(v => v.status === 'AVAILABLE').map(v => <option key={v.id} value={v.id}>{v.vehicleNumber} · {v.type}</option>)}</select><select className="form-input" value="" disabled={busy} onChange={e => { const paramedicId = e.target.value; confirm('Assign paramedic?', () => api('POST', `/admin/emergencies/${d.id}/assign-paramedic`, { paramedicId })); }}><option value="">Select paramedic</option>{paramedics.filter(p => p.status === 'ACTIVE' && p.paramedic?.verificationStatus === 'VERIFIED').map(p => <option key={p.id} value={p.paramedic.id}>{p.fullName}</option>)}</select></>}
          {!d.admissions.length && d.status !== 'CANCELLED' && <button className="btn btn-primary" disabled={busy} onClick={() => confirm('Record admission request?', () => api('POST', `/dispatch/${d.id}/admission`, {}))}>Request Hospital Admission</button>}
          {d.admissions.map((a: any) => <div key={a.id}><p>Admission: {a.status} {a.dischargeNotes && `· ${a.dischargeNotes}`}</p>{a.status !== 'DISCHARGED' && <button className="btn btn-success" disabled={busy} onClick={() => confirm(a.status === 'REQUESTED' ? 'Confirm admitted?' : 'Record discharge and create follow-up draft?', note => api('PUT', `/admissions/${a.id}/status`, { status: a.status === 'REQUESTED' ? 'ADMITTED' : 'DISCHARGED', dischargeNotes: note }))}>{a.status === 'REQUESTED' ? 'Confirm Admitted' : 'Record Discharge'}</button>}</div>)}
        </div>;
      })}
      {loaded && !dispatches.some(d => history || transitions[d.status]) && <p>No dispatches in this view.</p>}
    </div>
    {vehicle && <div className="modal-overlay"><form className="modal" onSubmit={e => { e.preventDefault(); void run(async () => { await api(vehicle.id ? 'PUT' : 'POST', `/admin/ambulances${vehicle.id ? `/${vehicle.id}` : ''}`, { vehicleNumber: vehicle.vehicleNumber, plateNumber: vehicle.plateNumber, type: vehicle.type, provider: vehicle.provider, contactNumber: vehicle.contactNumber, ...(vehicle.status !== 'DISPATCHED' ? { status: vehicle.status } : {}) }); setVehicle(null); }); }}><h3>{vehicle.id ? 'Edit' : 'Register'} Ambulance</h3>{['vehicleNumber', 'plateNumber', 'provider', 'contactNumber'].map(key => <label key={key} className="form-group">{({ vehicleNumber: 'Vehicle number', plateNumber: 'Plate number', provider: 'Provider', contactNumber: 'Contact number' } as Record<string, string>)[key]}<input className="form-input" required={['vehicleNumber', 'plateNumber'].includes(key)} value={vehicle[key] || ''} onChange={e => setVehicle({ ...vehicle, [key]: e.target.value })} /></label>)}<label>Type<select className="form-input" value={vehicle.type} onChange={e => setVehicle({ ...vehicle, type: e.target.value })}>{['BASIC', 'ADVANCED', 'ICU'].map(t => <option key={t}>{t}</option>)}</select></label>{vehicle.status !== 'DISPATCHED' && <label>Status<select className="form-input" value={vehicle.status} onChange={e => setVehicle({ ...vehicle, status: e.target.value })}>{['AVAILABLE', 'INACTIVE'].map(s => <option key={s}>{s}</option>)}</select></label>}{error && <p role="alert">{error}</p>}<button type="button" className="btn btn-ghost" disabled={busy} onClick={() => setVehicle(null)}>Cancel</button><button className="btn btn-primary" disabled={busy}>Save</button></form></div>}
    {hospital && <div className="modal-overlay"><form className="modal" onSubmit={e => { e.preventDefault(); void run(async () => { await api(hospital.id ? 'PUT' : 'POST', `/admin/hospitals${hospital.id ? `/${hospital.id}` : ''}`, { name: hospital.name, latitude: Number(hospital.latitude), longitude: Number(hospital.longitude), capacityStatus: hospital.capacityStatus, affordabilityTier: hospital.affordabilityTier, isCharity: hospital.isCharity }); setHospital(null); }); }}><h3>Hospital Details & Capacity</h3><label>Name<input className="form-input" required value={hospital.name} onChange={e => setHospital({ ...hospital, name: e.target.value })} /></label>{['latitude', 'longitude'].map(key => <label key={key}>{key}<input className="form-input" type="number" step="any" min={key === 'latitude' ? -90 : -180} max={key === 'latitude' ? 90 : 180} required value={hospital[key]} onChange={e => setHospital({ ...hospital, [key]: e.target.value })} /></label>)}<label>Capacity<select className="form-input" value={hospital.capacityStatus} onChange={e => setHospital({ ...hospital, capacityStatus: e.target.value })}>{['AVAILABLE', 'LIMITED', 'FULL'].map(s => <option key={s}>{s}</option>)}</select></label><label>Budget<select className="form-input" value={hospital.affordabilityTier} onChange={e => setHospital({ ...hospital, affordabilityTier: e.target.value })}>{['LOW', 'MEDIUM', 'HIGH'].map(s => <option key={s}>{s}</option>)}</select></label><label><input type="checkbox" checked={hospital.isCharity} onChange={e => setHospital({ ...hospital, isCharity: e.target.checked })} /> Charity</label>{error && <p role="alert">{error}</p>}<button type="button" className="btn btn-ghost" disabled={busy} onClick={() => setHospital(null)}>Cancel</button><button className="btn btn-primary" disabled={busy}>Save Capacity Update</button></form></div>}
    {confirmation && <div className="modal-overlay"><div className="modal" role="dialog" aria-modal="true"><h3>{confirmation.title}</h3><textarea className="form-input" placeholder="Notes (optional)" value={notes} onChange={e => setNotes(e.target.value)} />{error && <p role="alert">{error}</p>}<button className="btn btn-ghost" disabled={busy} onClick={() => setConfirmation(null)}>Cancel</button><button className="btn btn-primary" disabled={busy} onClick={() => void run(() => confirmation.run(notes))}>{busy ? 'Saving…' : 'Confirm'}</button></div></div>}
  </div>;
}
