import { qaToken } from './qa-session';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcrypt';
import app from '../../src/app';
import { prisma } from '../../src/common/config/database';
import { config } from '../../src/common/config';
import { DoctorRepository } from '../../src/domains/identity/doctor/doctor.repository';
import { logger } from '../../src/common/utils/logger';
async function main() {
 require('../dev/jest-isolation.cjs');
 const eligible = DoctorRepository.findEligibleDoctorsWithWorkload;
 logger.silent=true; const users:string[]=[], files:string[]=[], requests:string[]=[]; const password=randomUUID();
 const server=app.listen(0,'127.0.0.1'); await new Promise<void>(r=>server.once('listening',r)); const base=`http://127.0.0.1:${(server.address() as any).port}/api/v1`;
 const raw=async(a:any,m:string,u:string,b?:any)=>fetch(base+u,{method:m,headers:{Authorization:'Bearer '+await qaToken(a),...(b instanceof FormData?{}:{'Content-Type':'application/json'})},...(b===undefined?{}:{body:b instanceof FormData?b:JSON.stringify(b)})});
 const req=async(a:any,m:string,u:string,b?:any,status=200)=>{const r=await raw(a,m,u,b);const j=await r.json();assert.equal(r.status,status,`${m} ${u}: ${j.message}`);return j.data;};
 const create=async(role:any,pending=false)=>{const id=randomUUID();const u=await prisma.user.create({data:{id,email:`${id}@healix-test.invalid`,phone:`qa-${id}`,fullName:`Workflow QA ${role}`,passwordHash:await bcrypt.hash(password,4),role,status:pending?'PENDING_VERIFICATION':'ACTIVE',...(role==='PATIENT'?{patient:{create:{cnic:id}}}:{}),...(role==='NURSE'?{nurse:{create:{cnic:id,pncNumber:id,verificationStatus:pending?'PENDING':'VERIFIED'}}}:{}),...(role==='DOCTOR'?{doctor:{create:{cnic:id,pmdcNumber:id,verificationStatus:'VERIFIED'}}}:{}),...(role==='ADMIN'?{admin:{create:{}}}:{})},include:{patient:true,nurse:true,doctor:true}});users.push(id);return u;};
 try {
 const patient=await create('PATIENT'), outsider=await create('PATIENT'), nurse=await create('NURSE'), pending=await create('NURSE',true), doctor=await create('DOCTOR'), admin=await create('ADMIN');const pid=patient.patient!.id,nid=nurse.nurse!.id,pendingId=pending.nurse!.id;
 DoctorRepository.findEligibleDoctorsWithWorkload = async (tx?: any) => (tx || prisma).doctor.findMany({ where: { id: doctor.doctor!.id }, include: { availabilities: true, _count: { select: { caseAssignments: true } } } });
 const login=await fetch(base+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({emailOrPhone:pending.email,password})});assert.equal(login.status,200,await login.text());
 await req(pending,'GET','/auth/me');await req(pending,'GET',`/nurses/${pendingId}/profile`);await req(pending,'GET',`/nurses/${pendingId}/visits`,undefined,403);await req(pending,'GET',`/patients/${pid}/profile`,undefined,403);await req(pending,'PUT',`/nurses/${pendingId}/profile`,{available:true},403);
 await req(nurse,'POST',`/nurses/${nid}/availability`,{dayOfWeek:1,startTime:'99:00',endTime:'99:30'},400);assert.equal((await req(nurse,'POST',`/nurses/${nid}/availability`,{dayOfWeek:1,startTime:'17:00',endTime:'23:00',shiftType:'NIGHT'},201)).shiftType,'NIGHT');await req(nurse,'POST',`/nurses/${nid}/availability`,{dayOfWeek:1,startTime:'18:00',endTime:'20:00'},409);
 await req(patient,'PUT',`/patients/${pid}/profile`,{fullName:'Patient workflow QA',dob:'1995-02-28',address:'QA address',latitude:0,longitude:0});await req(patient,'PUT',`/patients/${pid}/profile`,{dob:'2026-02-29'},400);
 const location=await req(patient,'PUT',`/patients/${pid}/profile`,{city:'Lahore',address:'QA new address'});assert.equal(location.city,'Lahore');assert.equal(location.latitude,null);assert.equal(location.longitude,null);
 await req(patient,'PUT',`/patients/${pid}/profile`,{latitude:31.5},400);
 await req(patient,'PUT',`/patients/${pid}/profile`,{latitude:0,longitude:0});
 const scheduledRequest=await prisma.careRequest.create({data:{patientId:pid,type:'NURSE_VISIT',status:'OPEN',preferredDate:new Date(Date.now()+86400000)}});
 const rescheduled=await req(patient,'PUT',`/patients/requests/${scheduledRequest.id}/reschedule`,{scheduledAt:new Date(Date.now()+172800000).toISOString()});assert(rescheduled.scheduledAt);
 await req(patient,'PUT',`/patients/requests/${scheduledRequest.id}/cancel`,{});
 await req(patient,'PUT',`/patients/requests/${scheduledRequest.id}/reschedule`,{scheduledAt:new Date(Date.now()+259200000).toISOString()},409);
 const gpsRequest=await prisma.careRequest.create({data:{patientId:pid,type:'NURSE_VISIT',status:'OPEN',latitude:31.5,longitude:74.3}});
 const gpsVisit=await prisma.visit.create({data:{requestId:gpsRequest.id,nurseId:nid,status:'SCHEDULED'}});
 await req(nurse,'POST',`/visits/${gpsVisit.id}/verify-gps`,{lat:31.5,lng:74.3});
 assert.equal((await prisma.visit.findUniqueOrThrow({where:{id:gpsVisit.id}})).status,'IN_PROGRESS');
 await req(patient,'PUT',`/patients/requests/${gpsRequest.id}/cancel`,{},400);
 const contact=await req(patient,'POST',`/patients/${pid}/emergency-contacts`,{name:'QA Contact',phone:'+923001234567',relationship:'Family'},201);await req(outsider,'DELETE',`/patients/${pid}/emergency-contacts/${contact.id}`,undefined,403);await req(patient,'DELETE',`/patients/${pid}/emergency-contacts/${contact.id}`);
 await req(patient,'POST',`/patients/${pid}/conditions`,{name:'QA recorded condition',diagnosedDate:'2025-01-01'},201);await req(patient,'POST',`/patients/${pid}/allergies`,{allergen:'QA allergen',severity:'SEVERE'},201);const medication=await req(patient,'POST',`/patients/${pid}/medications`,{name:'QA medication',dosage:'5 mg',frequency:'Once daily'},201);
 const medical=await req(patient,'GET',`/patients/${pid}/medical-history`);assert.equal(medical.allergies.length,1);assert.equal(medical.chronicConditions.length,1);
 const plan=await prisma.carePlan.create({data:{patientId:pid,doctorId:doctor.doctor!.id,title:'QA progress plan',milestones:{create:[{title:'First milestone',targetDate:new Date()},{title:'Second milestone',targetDate:new Date()}]}},include:{milestones:true}});
 const plans=await req(patient,'GET',`/patients/${pid}/care-plans`);assert.equal(plans.find((p:any)=>p.id===plan.id).milestones.length,2);
 await req(outsider,'PUT',`/care-plans/milestones/${plan.milestones[0].id}/complete`,{},403);
 const halfway=await req(patient,'PUT',`/care-plans/milestones/${plan.milestones[0].id}/complete`,{});assert.equal(halfway.progress,50);assert.equal(halfway.status,'ACTIVE');
 const replay=await req(patient,'PUT',`/care-plans/milestones/${plan.milestones[0].id}/complete`,{});assert.equal(replay.progress,50);
 const finished=await req(patient,'PUT',`/care-plans/milestones/${plan.milestones[1].id}/complete`,{});assert.equal(finished.progress,100);assert.equal(finished.status,'COMPLETED');
 const revision={version:1,reason:'QA revised treatment milestone plan',title:'QA revised plan',description:'Revised treatment',milestones:[...plan.milestones.map(item=>({id:item.id,title:item.title,targetDate:item.targetDate.toISOString()})),{title:'New follow-up milestone',targetDate:new Date(Date.now()+86400000).toISOString()}]};
 await req(patient,'PUT',`/care-plans/${plan.id}`,revision,403);await req(nurse,'PUT',`/care-plans/${plan.id}`,revision,403);
 const revised=await req(doctor,'PUT',`/care-plans/${plan.id}`,revision);assert.equal(revised.version,2);assert.equal(revised.milestones.length,3);assert.equal(Math.round(revised.progress),67);assert.equal(revised.status,'ACTIVE');
 await req(doctor,'PUT',`/care-plans/${plan.id}`,revision,409);
 await req(doctor,'PUT',`/care-plans/${plan.id}`,{...revision,version:2,milestones:revision.milestones.slice(2)},409);
 const history=await req(patient,'GET',`/care-plans/${plan.id}/history`);assert.equal(history.history.length,2);assert.equal(history.history[1].snapshot.title,'QA progress plan');await req(outsider,'GET',`/care-plans/${plan.id}/history`,undefined,403);
 const editPayload={...revision,version:2,milestones:revised.milestones.map((item:any)=>({id:item.id,title:item.title,targetDate:item.targetDate}))};const concurrent=await Promise.all([raw(doctor,'PUT',`/care-plans/${plan.id}`,{...editPayload,title:'QA concurrent A'}),raw(doctor,'PUT',`/care-plans/${plan.id}`,{...editPayload,title:'QA concurrent B'})]);assert.deepEqual(concurrent.map(response=>response.status).sort(),[200,409]);assert.equal((await req(patient,'GET',`/care-plans/${plan.id}/history`)).history.length,3);

 const futureDoseTime=new Date(Date.now()+86400000).toISOString();assert.equal((await req(patient,'POST',`/patients/${pid}/medications/${medication.id}/schedule`,{times:[futureDoseTime]},201)).added,1);assert.equal((await req(patient,'POST',`/patients/${pid}/medications/${medication.id}/schedule`,{times:[futureDoseTime]},201)).added,0);await req(outsider,'POST',`/patients/${pid}/medications/${medication.id}/schedule`,{times:[futureDoseTime]},403);
 const futureDose=await prisma.medicationDose.findFirstOrThrow({where:{medicationId:medication.id}});await req(patient,'PUT',`/patients/${pid}/medication-doses/${futureDose.id}`,{status:'TAKEN'},409);
 const dosePage=await req(patient,'GET',`/patients/${pid}/medication-doses?limit=1&page=1`);assert.equal(dosePage.total,1);assert.equal(dosePage.items[0].id,futureDose.id);assert.equal(dosePage.page,1);assert.equal(dosePage.limit,1);await req(outsider,'GET',`/patients/${pid}/medication-doses`,undefined,403);
 const dueDose=await prisma.medicationDose.create({data:{medicationId:medication.id,scheduledAt:new Date(Date.now()-3600000)}});await prisma.medicationDose.create({data:{medicationId:medication.id,scheduledAt:new Date(Date.now()-1800000)}});
 await req(patient,'PUT',`/patients/${pid}/medication-doses/${dueDose.id}`,{status:'TAKEN'});await req(patient,'PUT',`/patients/${pid}/medication-doses/${dueDose.id}`,{status:'TAKEN'});assert.equal(await prisma.medicationLog.count({where:{scheduledDoseId:dueDose.id}}),1);
 const priorRequest=await prisma.careRequest.create({data:{patientId:pid,type:'NURSE_VISIT',scheduledAt:new Date(Date.now()-3*86400000),status:'ASSIGNED',visits:{create:[{nurseId:nid,status:'COMPLETED',completedAt:new Date(),agreedStartTime:new Date(Date.now()-2*86400000)},{nurseId:nid,status:'SCHEDULED',agreedStartTime:new Date(Date.now()-86400000)}]}}});requests.push(priorRequest.id);
 const adherence=await req(patient,'GET',`/patients/${pid}/compliance`);assert.equal(adherence.medicationCompliance,50);assert.equal(adherence.dueDoses,2);assert.equal(adherence.medicationTimingCompliance,50);assert.equal(adherence.visitCompliance,50);assert.equal(adherence.dueVisits,2);assert.equal(adherence.trend,'INSUFFICIENT_DATA');

 const future=new Date(Date.now()+86400000);const care=await prisma.careRequest.create({data:{patientId:pid,type:'NURSE_VISIT',scheduledAt:future,visits:{create:{nurseId:nid}}},include:{visits:true}});requests.push(care.id);const vid=care.visits[0].id;const careContract=await prisma.contract.create({data:{patientId:pid,nurseId:nid,careRequestId:care.id,price:100,priceType:'FIXED',scopeText:'QA care scope',status:'ACTIVE',patientApproved:true,nurseApproved:true,expiresAt:future}});
 const dates={startDate:new Date(future.getTime()-3600000).toISOString(),endDate:new Date(future.getTime()+3600000).toISOString()};await req(nurse,'POST',`/nurses/${nid}/vacations`,dates,409);
 await req(patient,'POST',`/visits/${vid}/accept`,{},403);await req(nurse,'POST',`/visits/${vid}/accept`,{});await req(nurse,'POST',`/visits/${vid}/verify-manual`,{reason:'QR cannot be used for this visit.'},409);await req(outsider,'PUT',`/visits/${vid}/confirm-arrival`,{},400);await req(patient,'PUT',`/visits/${vid}/confirm-arrival`,{});await req(nurse,'POST',`/visits/${vid}/verify-manual`,{reason:'QR cannot be used for this visit.'});
 const draft={id:randomUUID(),kind:'VITALS',capturedAt:new Date().toISOString(),data:{systolic:119,diastolic:79,heartRate:74,temperature:37,oxygenSaturation:98}};
 const evidencePng=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/lN8AAAAASUVORK5CYII=','base64');
 const evidenceForm=(consent='true')=>{const form=new FormData();form.append('file',new Blob([evidencePng],{type:'image/png'}),'qa.png');form.append('type','PHOTO');form.append('consentGiven',consent);return form;};
 await req(nurse,'POST',`/visits/${vid}/evidence/file`,evidenceForm('false'),400);
 await req(outsider,'POST',`/visits/${vid}/evidence/file`,evidenceForm(),403);
 const evidence=await req(nurse,'POST',`/visits/${vid}/evidence/file`,evidenceForm(),201);
 files.push(path.resolve('private','visit-evidence',process.env.HEALIX_TEST_SCHEMA!,vid,evidence.urlOrText.slice(8)));
 assert.equal((await raw(patient,'GET',`/visits/${vid}/evidence/${evidence.id}/file`)).status,200);await req(outsider,'GET',`/visits/${vid}/evidence/${evidence.id}/file`,undefined,403);
 await req(patient,'PUT',`/visits/${vid}/completion-review`,{decision:'APPROVE'},409);
 await req(patient,'POST',`/visits/${vid}/clinical-sync`,draft,403);
 assert.equal((await req(nurse,'POST',`/visits/${vid}/clinical-sync`,draft)).replayed,false);
 assert.equal((await req(nurse,'POST',`/visits/${vid}/clinical-sync`,draft)).replayed,true);
 await req(nurse,'POST',`/visits/${vid}/clinical-sync`,{...draft,data:{...draft.data,heartRate:80}},409);
 assert.equal(await prisma.vitalsRecord.count({where:{id:draft.id}}),1);
 const symptomsDraft={id:randomUUID(),kind:'SYMPTOMS',capturedAt:new Date().toISOString(),data:{symptoms:[{symptomName:'QA first',severity:'MILD'},{symptomName:'QA second',severity:'MODERATE',notes:'QA note'}]}};
 await req(nurse,'POST',`/visits/${vid}/clinical-sync`,symptomsDraft);assert.equal((await req(nurse,'POST',`/visits/${vid}/clinical-sync`,symptomsDraft)).replayed,true);
 await req(nurse,'POST',`/visits/${vid}/vitals`,{systolic:120,diastolic:80,heartRate:75,temperature:37,oxygenSaturation:98});await req(nurse,'POST',`/visits/${vid}/symptoms`,{symptoms:[{symptomName:'QA symptom',severity:'MILD'}]});await req(nurse,'POST',`/visits/${vid}/clinical-remarks`,{remarksText:'QA clinical workflow documentation.',confidenceLevel:3});await req(nurse,'POST',`/visits/${vid}/complete`,{});
 await req(patient,'PUT',`/visits/${vid}/completion-review`,{decision:'APPROVE'},409);
 await req(nurse,'POST',`/visits/${vid}/evidence/file`,evidenceForm(),409);
 const checkout=await req(nurse,'PUT',`/visits/${vid}/check-out`,{});assert.equal((await req(nurse,'PUT',`/visits/${vid}/check-out`,{})).checkOutAt,checkout.checkOutAt);
 await req(outsider,'PUT',`/visits/${vid}/completion-review`,{decision:'APPROVE'},403);
 await req(patient,'PUT',`/visits/${vid}/completion-review`,{decision:'DISPUTE',reason:'QA recorded completion concern'});
 const approval=await req(patient,'PUT',`/visits/${vid}/completion-review`,{decision:'APPROVE'});assert(approval.completionApprovedAt);assert.equal((await prisma.contract.findUniqueOrThrow({where:{id:careContract.id}})).status,'COMPLETED');assert.equal(approval.completionDisputeReason,null);assert.equal((await req(patient,'PUT',`/visits/${vid}/completion-review`,{decision:'APPROVE'})).completionApprovedAt,approval.completionApprovedAt);
 await req(patient,'PUT',`/visits/${vid}/completion-review`,{decision:'DISPUTE',reason:'QA later concern'},409);
 await req(outsider,'POST',`/visits/${vid}/rating`,{stars:5},403);await req(patient,'POST',`/visits/${vid}/rating`,{stars:5,reviewText:'QA feedback',recommend:true});await req(patient,'POST',`/visits/${vid}/rating`,{stars:5},400);const score=await req(nurse,'GET',`/nurses/${nid}/score`);assert.equal(score.onTimeRate,100);assert.equal(score.recommendationRate,100);
 assert.equal((await req(nurse,'POST',`/visits/${vid}/clinical-sync`,draft)).replayed,true);
 await req(nurse,'POST',`/visits/${vid}/clinical-sync`,{...draft,id:randomUUID()},409);
 const second=await prisma.visit.create({data:{requestId:care.id,nurseId:nid,status:'COMPLETED',completedAt:new Date()}});await prisma.payment.create({data:{requestId:care.id,amount:180,status:'PAID',paidAt:new Date()}});const earnings=await req(nurse,'GET',`/nurses/${nid}/earnings`);assert.equal(earnings.totalEarned,180);assert.equal(earnings.history.length,1);assert.equal((await req(patient,'GET',`/patients/${pid}/payments`)).length,1);await req(outsider,'GET',`/patients/${pid}/payments`,undefined,403);
 const vacation=await req(nurse,'POST',`/nurses/${nid}/vacations`,dates);await req(nurse,'POST',`/nurses/${nid}/vacations`,dates,409);await req(nurse,'DELETE',`/nurses/${nid}/vacations/${vacation.id}`);
 const rx=await prisma.prescription.create({data:{patientId:pid,visitId:second.id,doctorId:doctor.doctor!.id,fileUrl:'',instructions:'QA instructions (carefully).',items:{create:{medicationName:'QA medication',dosage:'QA dose',frequency:'QA frequency',durationDays:3}}}});assert.equal((await req(patient,'GET',`/patients/${pid}/prescriptions`))[0].items.length,1);const pdf=await raw(patient,'GET',`/patients/${pid}/prescriptions/${rx.id}/pdf`);assert.equal(pdf.status,200);assert.equal(pdf.headers.get('content-type'),'application/pdf');const bytes=Buffer.from(await pdf.arrayBuffer());assert(bytes.toString().startsWith('%PDF-1.4'));assert(bytes.includes(Buffer.from('QA medication')));await fs.writeFile('../scratch/nurse-patient-prescription-test.pdf',bytes);await req(outsider,'GET',`/patients/${pid}/prescriptions/${rx.id}/pdf`,undefined,403);
 assert((await req(patient,'GET',`/patients/${pid}/home-visits/doctors`)).some((d:any)=>d.id===doctor.doctor!.id));const home=await req(patient,'POST',`/patients/${pid}/home-visits`,{doctorId:doctor.doctor!.id,scheduledAt:future.toISOString()},201);assert.equal(home.status,'REQUESTED');await req(doctor,'PUT',`/doctors/home-visits/${home.id}`,{status:'EN_ROUTE'},409);await req(doctor,'PUT',`/doctors/home-visits/${home.id}`,{status:'SCHEDULED'});await req(doctor,'GET',`/patients/${pid}/medical-history`);await req(patient,'PUT',`/patients/${pid}/home-visits/${home.id}/cancel`,{});await req(outsider,'GET',`/patients/${pid}/home-visits`,undefined,403);
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/lN8AAAAASUVORK5CYII=','base64');const form=(type?:string)=>{const f=new FormData();f.append('file',new Blob([png],{type:'image/png'}),'qa.png');if(type)f.append('documentType',type);return f;};
 const photo=await req(nurse,'POST',`/nurses/${nid}/photo`,form());files.push(path.resolve('public/uploads/nurses',new URL(photo.photoUrl).pathname.split('/').pop()!));
 for(const type of ['CNIC_FRONT','CNIC_BACK','NURSE_LICENSE','DEGREE','BACKGROUND_CHECK']){const doc=await req(pending,'POST',`/nurses/${pendingId}/verification/file`,form(type),201);const url=new URL(doc.fileUrl);files.push(path.resolve('private/nurse-assets',pendingId,url.pathname.split('/').pop()!));assert.equal((await raw(pending,'GET',url.pathname.replace('/api/v1',''))).status,200);await req(outsider,'GET',url.pathname.replace('/api/v1',''),undefined,403);await req(nurse,'PUT','/nurses/verification/review',{documentId:doc.id,status:'APPROVED'},403);await req(admin,'PUT','/nurses/verification/review',{documentId:doc.id,status:'APPROVED'});}
 assert.equal((await prisma.user.findUniqueOrThrow({where:{id:pending.id}})).status,'ACTIVE');assert.equal((await prisma.nurse.findUniqueOrThrow({where:{id:pendingId}})).verificationStatus,'VERIFIED');const spec=await req(nurse,'POST',`/nurses/${nid}/specializations`,{specialization:'WOUND_CARE'},201);await req(nurse,'PUT',`/nurses/${nid}/specializations/${spec.id}/certificate`,{certificateUrl:'https://example.invalid/qa-certificate.pdf'});await req(nurse,'PUT',`/nurses/${nid}/specializations/${spec.id}/review`,{certified:true},403);await req(admin,'PUT',`/nurses/${nid}/specializations/${spec.id}/review`,{certified:true});assert((await req(nurse,'GET',`/nurses/${nid}/badges`)).some((b:any)=>b.badgeType==='WOUND_CARE_EXPERT'));
 await req(nurse,'PUT',`/nurses/${nid}/specializations/${spec.id}/assessment`,{rating:4,notes:'QA observed skill assessment evidence'},403);await req(admin,'PUT',`/nurses/${nid}/specializations/${spec.id}/assessment`,{rating:4,notes:'QA observed skill assessment evidence'});const assessed=await req(nurse,'GET',`/nurses/${nid}/score`);assert.equal(assessed.skillScore,80);assert.equal(assessed.skillAssessmentCount,1);await req(admin,'PUT',`/nurses/${nid}/specializations/${spec.id}/review`,{certified:false});assert.equal((await req(nurse,'GET',`/nurses/${nid}/score`)).skillAssessmentCount,0);

 const dashboard=await req(patient,'GET',`/patients/${pid}/dashboard`);assert.equal(dashboard.severeAllergiesCount,1);assert.equal(typeof dashboard.activeContractsCount,'number');assert.equal((await req(patient,'GET',`/patients/${pid}/vitals-history`)).length,2);await req(outsider,'GET',`/patients/${pid}/dashboard`,undefined,403);
 const patientReport=await req(patient,'GET','/analytics/overview');assert.equal(patientReport.role,'PATIENT');assert.equal(patientReport.tables.find((t:any)=>t.title==='Vital trends').rows.length,2);
 const outsideReport=await req(outsider,'GET',`/analytics/overview?patientId=${pid}`);assert.equal(outsideReport.tables.find((t:any)=>t.title==='Vital trends').rows.length,0);
 assert.equal((await req(nurse,'GET','/analytics/overview')).role,'NURSE');assert.equal((await req(doctor,'GET','/analytics/overview')).role,'DOCTOR');
 await req(patient,'GET',`/analytics/overview?staffUserId=${doctor.id}`,undefined,403);
 const nurseMonitor=await req(admin,'GET',`/analytics/overview?staffUserId=${nurse.id}`);assert.equal(nurseMonitor.role,'NURSE');assert.equal(nurseMonitor.tables[0].rows[0].userId,nurse.id);
 const doctorMonitor=await req(admin,'GET',`/analytics/overview?staffUserId=${doctor.id}`);assert.equal(doctorMonitor.role,'DOCTOR');await req(admin,'GET',`/analytics/overview?staffUserId=${patient.id}`,undefined,404);
 const adminReport=await req(admin,'GET','/analytics/overview');assert.equal(adminReport.metrics.find((m:any)=>m.label==='Recorded paid amounts in period').value,180);assert.equal(adminReport.metrics.find((m:any)=>m.label==='Recorded platform commission').value,null);
 await req(patient,'GET','/analytics/overview?from=2026-02-30',undefined,400);
 await prisma.carePlan.update({where:{id:plan.id},data:{title:'=1+1'}});
 const csv=await raw(patient,'GET','/analytics/report.csv');assert.equal(csv.status,200);assert(csv.headers.get('content-type')?.includes('text/csv'));assert((await csv.text()).includes("\"'=1+1\""));
 const adminUsers=await req(admin,'GET','/admin/users');assert(!JSON.stringify(adminUsers).includes('passwordHash'));assert(!JSON.stringify(await req(admin,'GET',`/admin/users/${pending.id}`)).includes('refreshTokenHash'));
 await req(patient,'PUT',`/admin/users/${patient.id}/profile`,{fullName:'Forbidden edit',reason:'QA reason for denied profile'},403);
 const edited=await req(admin,'PUT',`/admin/users/${patient.id}/profile`,{fullName:'QA updated patient',reason:'QA corrected patient profile name'});assert.equal(edited.fullName,'QA updated patient');assert(!JSON.stringify(edited).includes('passwordHash'));
 await req(admin,'PUT',`/admin/users/${patient.id}/profile`,{fullName:'QA updated patient',role:'ADMIN',reason:'QA attempted role escalation'},400);
 const unverified=await create('NURSE',true);await req(admin,'PUT',`/admin/users/${unverified.id}/status`,{status:'ACTIVE',reason:'QA premature activation check'},409);
 await req(patient,'GET','/admin/operations/monitor',undefined,403);assert.equal(typeof (await req(admin,'GET','/admin/operations/monitor')).uptimeSeconds,'number');
 const payment=await prisma.payment.findUniqueOrThrow({where:{requestId:care.id}});const refundBody={requestKey:randomUUID(),kind:'REFUND',paymentId:payment.id,amount:100,reason:'QA request for recorded refund'};
 await req(outsider,'POST','/support/cases',{...refundBody,requestKey:randomUUID()},403);const refund=await req(patient,'POST','/support/cases',refundBody,201);assert.equal((await req(patient,'POST','/support/cases',refundBody,201)).id,refund.id);
 await req(patient,'POST','/support/cases',{...refundBody,requestKey:randomUUID(),amount:81},409);
 await req(patient,'PUT',`/admin/support/cases/${refund.id}`,{status:'APPROVED',notes:'QA attempted unauthorized approval'},403);
 await req(admin,'PUT',`/admin/support/cases/${refund.id}`,{status:'RECORDED',notes:'QA invalid direct recorded transition'},409);
 await req(admin,'PUT',`/admin/support/cases/${refund.id}`,{status:'APPROVED',notes:'QA approved recorded refund request'});
 await req(admin,'PUT',`/admin/support/cases/${refund.id}`,{status:'RECORDED',notes:'QA missing external refund reference'},400);
 const refundRecord={status:'RECORDED',notes:'QA external refund ledger fixture only',externalReference:'QA-EXTERNAL-REFUND',completedAt:new Date().toISOString()};await req(admin,'PUT',`/admin/support/cases/${refund.id}`,refundRecord);await req(admin,'PUT',`/admin/support/cases/${refund.id}`,refundRecord);
 await req(admin,'PUT',`/admin/support/cases/${refund.id}`,{status:'REJECTED',notes:'QA attempted closed case modification'},409);
 assert.equal((await req(outsider,'GET','/support/cases')).items.length,0);assert((await req(patient,'GET','/support/cases')).items.some((item:any)=>item.visitId===vid && item.kind==='DISPUTE'));
 const commission={amount:18,reference:'QA-EXTERNAL-COMMISSION',recordedAt:new Date().toISOString(),reason:'QA recorded commission ledger fixture'};
 await req(patient,'PUT',`/admin/payments/${payment.id}/commission`,commission,403);await req(admin,'PUT',`/admin/payments/${payment.id}/commission`,{...commission,amount:181},400);await req(admin,'PUT',`/admin/payments/${payment.id}/commission`,commission);await req(admin,'PUT',`/admin/payments/${payment.id}/commission`,commission);await req(admin,'PUT',`/admin/payments/${payment.id}/commission`,{...commission,amount:19},409);
 const financial=await req(admin,'GET','/analytics/overview');assert.equal(financial.metrics.find((m:any)=>m.label==='Recorded platform commission').value,18);assert.equal(financial.metrics.find((m:any)=>m.label==='Recorded external refunds').value,100);
 const permission={role:'PATIENT',feature:'ANALYTICS',operation:'READ',allowed:false,reason:'QA role capability denial test'};await req(patient,'PUT','/admin/permissions',permission,403);await req(admin,'PUT','/admin/permissions',permission);await req(patient,'GET','/analytics/overview',undefined,403);await req(admin,'PUT','/admin/permissions',{...permission,allowed:true});await req(patient,'GET','/analytics/overview');
 await req(admin,'PUT','/admin/permissions',{...permission,role:'PATIENT',feature:'PROFILE',operation:'READ',allowed:true});await req(outsider,'GET',`/patients/${pid}/medical-history`,undefined,403);
 console.log('PASS: real HTTP/database nurse and patient workflows, onboarding isolation, private documents, shifts, vacation conflicts, visit acceptance/verification/completion, feedback, computed scores, payment deduplication, prescription PDF, doctor appointments and certificate approval.');
 } finally {DoctorRepository.findEligibleDoctorsWithWorkload = eligible; await new Promise<void>(r=>server.close(()=>r()));await prisma.eventOutbox.deleteMany({where:{aggregateId:{in:requests}}});await prisma.user.deleteMany({where:{id:{in:users}}});for(const f of files){assert(f.startsWith(path.resolve(process.cwd())+path.sep));await fs.unlink(f).catch(()=>{});}await prisma.$disconnect();}
}
void main().catch(e=>{console.error(e);process.exitCode=1;});
