import { qaToken } from './qa-session';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import jwt from 'jsonwebtoken';
import app from '../../src/app';
import { prisma } from '../../src/common/config/database';
import { config } from '../../src/common/config';
import { MarketplaceRepository } from '../../src/domains/marketplace/marketplace/marketplace.repository';
import { logger } from '../../src/common/utils/logger';

async function main() {
 require('../dev/jest-isolation.cjs'); logger.silent = true;
 const server = app.listen(0, '127.0.0.1'); await new Promise<void>(resolve => server.once('listening', resolve));
 const base = `http://127.0.0.1:${(server.address() as any).port}/api/v1`;
 const raw = async (user:any, method:string, route:string, data?:any) => fetch(base + route, { method, headers: { Authorization: 'Bearer ' + await qaToken(user), 'Content-Type':'application/json' }, ...(data ? {body:JSON.stringify(data)} : {}) });
 const req = async(user:any, method:string, route:string, data?:any, status=200) => { const response=await raw(user,method,route,data); const body=await response.json(); assert.equal(response.status,status,`${method} ${route}: ${body.message}`); return body.data; };
 const create = async(role:'PATIENT'|'NURSE') => { const id=randomUUID(); return prisma.user.create({data:{id,email:`${id}@healix-test.invalid`,phone:id,passwordHash:'unused-test-password',fullName:'Marketplace QA',role,status:'ACTIVE',...(role==='PATIENT'?{patient:{create:{cnic:id,address:'Private street, Lahore',city:'Lahore'}}}:{nurse:{create:{cnic:id,pncNumber:id,verificationStatus:'VERIFIED'}}})},include:{patient:true,nurse:true}}); };
 try {
  const patient=await create('PATIENT'), outsider=await create('PATIENT'), nurse=await create('NURSE'), competitor=await create('NURSE');
  const listing = async(patientId:string) => { const care=await prisma.careRequest.create({data:{patientId,type:'NURSE_VISIT',status:'OPEN',durationMinutes:30,marketplaceListing:{create:{zone:'Private street',status:'OPEN'}}},include:{marketplaceListing:true}}); return care.marketplaceListing!; };
  const first=await listing(patient.patient!.id), other=await listing(outsider.patient!.id);
  const payload={price:1000,priceType:'HOURLY',proposedStart:new Date(Date.now()+86400000).toISOString(),message:'QA offer'};
  const offer=await req(nurse,'POST',`/marketplace/listings/${first.id}/offers`,payload);
  const bid=await req(competitor,'POST',`/marketplace/listings/${first.id}/offers`,{...payload,price:900});
  const foreign=await req(nurse,'POST',`/marketplace/listings/${other.id}/offers`,payload);
  await req(outsider,'GET',`/marketplace/listings/${first.id}/offers`,undefined,403);
  const mine=await req(nurse,'GET',`/marketplace/listings/${first.id}/offers`); assert.equal(mine.length,1); assert.equal(mine[0].id,offer.id); assert(!JSON.stringify(mine).includes('cnic')); assert(!JSON.stringify(mine).includes('pncNumber')); assert.equal(mine[0].estimatedServiceCost,500);
  const listings=await req(nurse,'GET','/marketplace/requests'); assert(!JSON.stringify(listings).includes('Private street')); assert.equal(listings.find((l:any)=>l.id===first.id).offers.length,1); assert.equal(listings.find((l:any)=>l.id===first.id).zone,'Lahore');
  assert.equal((await req(patient,'POST','/pricing/preview',{price:1000,priceType:'HOURLY',durationHours:0.5})).serviceCost,500);
  assert.equal((await req(patient,'POST','/pricing/preview',{price:1000,priceType:'DAILY',durationHours:25})).serviceCost,2000);
  assert.equal((await req(patient,'POST','/pricing/preview',{price:1000,priceType:'FIXED',durationHours:25})).serviceCost,1000);
  await req(patient,'POST',`/marketplace/listings/${first.id}/select`,{offerId:foreign.id},409);
  await req(outsider,'POST',`/offers/${bid.id}/reject`,{},403);
  await req(patient,'POST',`/offers/${bid.id}/reject`,{}); await req(competitor,'PUT',`/offers/${bid.id}`,{price:800},409);
  await req(nurse,'DELETE',`/offers/${offer.id}`); assert.equal((await req(nurse,'GET',`/marketplace/listings/${first.id}/offers`))[0].status,'WITHDRAWN');
  const again=await req(nurse,'POST',`/marketplace/listings/${first.id}/offers`,payload);
  const simultaneous=await Promise.all([req(patient,'POST',`/patients/${patient.patient!.id}/favorite-nurses`,{nurseId:nurse.nurse!.id}),req(patient,'POST',`/patients/${patient.patient!.id}/favorite-nurses`,{nurseId:nurse.nurse!.id})]); assert.equal(simultaneous[0].id,simultaneous[1].id);
  assert.equal((await req(patient,'GET',`/patients/${patient.patient!.id}/favorite-nurses`)).length,1); await req(outsider,'GET',`/patients/${patient.patient!.id}/favorite-nurses`,undefined,403);
  await req(patient,'DELETE',`/patients/${patient.patient!.id}/favorite-nurses/${nurse.nurse!.id}`); assert.equal((await req(patient,'GET',`/patients/${patient.patient!.id}/favorite-nurses`)).length,0);
  const next=await req(competitor,'POST',`/marketplace/listings/${first.id}/offers`,payload);
  const selections=await Promise.all([raw(patient,'POST',`/marketplace/listings/${first.id}/select`,{offerId:again.id}),raw(patient,'POST',`/marketplace/listings/${first.id}/select`,{offerId:next.id})]); assert.deepEqual(selections.map(r=>r.status).sort(),[200,409]);
  const selected=await prisma.offer.findFirstOrThrow({where:{listingId:first.id,status:'ACCEPTED'}}); assert.equal(await prisma.contract.count({where:{careRequestId:first.careRequestId}}),1);
  const selection=await req(patient,'POST',`/marketplace/listings/${first.id}/select`,{offerId:selected.id}); assert(selection.contractId);
  const cid=selection.contractId;
  const contract=await req(patient,'GET',`/contracts/${cid}`); assert(!JSON.stringify(contract).includes('cnic')); assert.equal(contract.auditLogs[0].action,'CREATED');
  await req(outsider,'GET',`/contracts/${cid}/audit-trail`,undefined,403); await req(outsider,'PUT',`/contracts/${cid}/approve`,{},403);
  const winner=selected.nurseId === nurse.nurse!.id ? nurse : competitor;
  assert.equal((await req(patient,'PUT',`/contracts/${cid}/approve`,{})).status,'PENDING_APPROVAL'); assert.equal((await req(winner,'PUT',`/contracts/${cid}/approve`,{})).status,'ACTIVE');
  assert.equal((await req(patient,'GET',`/contracts/${cid}/audit-trail`)).length,3);
  await req(outsider,'POST','/contracts',{patientId:patient.patient!.id,nurseId:nurse.nurse!.id,price:100,scopeText:'QA scope'},403);
  await req(nurse,'POST',`/marketplace/listings/${first.id}/offers`,payload,409);
  const expired=await prisma.offer.create({data:{...payload,proposedStart:new Date(payload.proposedStart),listingId:other.id,nurseId:competitor.nurse!.id,expiresAt:new Date(Date.now()-1000)}}); await req(outsider,'POST',`/marketplace/listings/${other.id}/select`,{offerId:expired.id},409);
  const { CreateVisitFromContractUseCase } = require('../../src/domains/care/visit/lifecycle/create-visit-from-contract.usecase');
  const maker=new CreateVisitFromContractUseCase(); const oldVisit=await maker.execute(cid);
  await req(patient,'PUT',`/contracts/${cid}/cancel`,{reason:'QA cancelled future agreement'});
  assert.equal((await prisma.visit.findUniqueOrThrow({where:{id:oldVisit.id}})).status,'CANCELLED');
  const replacement=await req(nurse,'POST',`/marketplace/listings/${first.id}/offers`,payload);
  const renewed=await req(patient,'POST',`/marketplace/listings/${first.id}/select`,{offerId:replacement.id}); assert.notEqual(renewed.contractId,cid);
  const historical=await req(patient,'GET',`/contracts/${cid}`); assert.equal(historical.status,'CANCELLED'); assert.equal(historical.originalCareRequestId,first.careRequestId); assert.equal(historical.careRequestId,null);
  assert.equal((await req(patient,'GET',`/contracts/${renewed.contractId}`)).patientApproved,false);
  await req(patient,'PUT',`/contracts/${renewed.contractId}/approve`,{}); await req(nurse,'PUT',`/contracts/${renewed.contractId}/approve`,{});
  const newVisit=await maker.execute(renewed.contractId); assert.notEqual(newVisit.id,oldVisit.id); assert.equal((await maker.execute(renewed.contractId)).id,newVisit.id);
  const { registerContractListeners }=require('../../src/domains/marketplace/contracts/contract.listeners'); const { registerVisitListeners }=require('../../src/domains/care/visit/visit.listeners'); const { AppEventBus,EVENTS }=require('../../src/common/events/app-event-bus'); registerContractListeners();registerVisitListeners();
  await AppEventBus.emitAsync(EVENTS.CONTRACT_CANCELLED,{contractId:cid}); await AppEventBus.emitAsync(EVENTS.VISIT_CANCELLED,{visitId:oldVisit.id,careRequestId:first.careRequestId});
  assert.equal((await prisma.contract.findUniqueOrThrow({where:{id:renewed.contractId}})).status,'ACTIVE'); assert.equal((await prisma.visit.findUniqueOrThrow({where:{id:newVisit.id}})).status,'SCHEDULED');
  await MarketplaceRepository.reopenListing(first.careRequestId); assert.equal((await prisma.offer.findUniqueOrThrow({where:{id:bid.id}})).status,'REJECTED'); assert.equal((await prisma.offer.findUniqueOrThrow({where:{id:offer.id}})).status,'WITHDRAWN');
  const { VisitRepository }=require('../../src/domains/care/visit/visit.repository');
  const race=await Promise.allSettled([VisitRepository.startVisit(newVisit.id,'GPS','QA concurrent arrival'),req(patient,'PUT',`/contracts/${renewed.contractId}/cancel`,{reason:'QA concurrent cancellation'})]);
  assert.equal(race.filter(result=>result.status==='fulfilled').length,1);
  const raceContract=await prisma.contract.findUniqueOrThrow({where:{id:renewed.contractId}}),raceVisit=await prisma.visit.findUniqueOrThrow({where:{id:newVisit.id}});
  assert((raceContract.status==='ACTIVE' && raceVisit.status==='IN_PROGRESS') || (raceContract.status==='CANCELLED' && raceVisit.status==='CANCELLED'));
  console.log('PASS: isolated marketplace HTTP workflows, privacy, ownership, price units, reject/withdraw, concurrent favorites and selection, terminal/expiry guards and contract creation.');
 } finally { await new Promise<void>(resolve=>server.close(()=>resolve())); await prisma.$disconnect(); }
}
void main().catch(error=>{console.error(error);process.exitCode=1;});
